### ISSUE TITLE
Did you do Data Augmentation?

### ISSUE THREAD

**Issue by wuqiangch** [fullfanta/CNN_based_Face_Alignment#1]
How many train images do you get  after do  Data Augmentation?

**Comment by fullfanta** [comment]
@wuqiangch

Before augmentation, I collected 3283 images from IBUG(135 images), AFW (337 images), LFPW (811 images), and HELEN (2000 images) of 300W.
I augmented 10 times from each image so that I trained 32830 images.

**Comment by wuqiangch** [comment]
@fullfanta you only use the landmarks to get face ,and dont use face detector?

**Comment by fullfanta** [comment]
@wuqiangch 

At the training time, I didn't use face detector. I tried opencv's face detector to get bounding box, but the result is very wrong. So I used only landmarks with scale, rotation, and translation augmentation.

But at the test time, I used opencv's face detector like **mxnet/predict.py**:
https://github.com/fullfanta/CNN_based_Face_Alignment/blob/master/mxnet/predict.py#L17-L33
