### ISSUE TITLE
the problem of im2rec

### ISSUE THREAD

**Issue by zhuhongweiyi** [fullfanta/CNN_based_Face_Alignment#2]
Could you tell how to run im2rec on windows?
I edit im2rec.sh as im2rec.bat, as follows:
@echo off
echo "Generating rec"
python D:/mxnet/mxnet/tools/im2rec.py ./training_data ../crop_images --pack-label=True
python D:/mxnet/mxnet/tools/im2rec.py ./test_data ../crop_images --pack-label=True
but couldn't succeed(im2rec.py didn't contain parameter label_width)
I hope you can reply me, thanks

**Comment by fullfanta** [comment]
@zhuhongweiyi 

I used https://github.com/dmlc/mxnet/blob/master/tools/im2rec.cc to record images and multi labels.
I didn't try mxnet on windows but I think you can compile im2rec.cc in windows and execute it.

**Comment by fullfanta** [comment]
@zhuhongweiyi 

In https://github.com/dmlc/mxnet/blob/master/tools/im2rec.py#L79-L87, you can see that each line on list file is split by '\t' automatically.

I think you don't need to give parameter 'label_width' in im2rec.py.

**Comment by zhuhongweiyi** [comment]
@fullfanta thanks，I try the method as follows:
@echo off
echo "Generating rec"
python D:/mxnet/mxnet/tools/im2rec.py training_data ./  --pack-label=True
python D:/mxnet/mxnet/tools/im2rec.py test_data ./  --pack-label=True
pause
but it also could't succeed
the problem is:
![image](https://cloud.githubusercontent.com/assets/13095770/21794549/36ae42b0-d736-11e6-965b-ac14a042779d.png)
Should I regenerate the lst?

**Comment by fullfanta** [comment]
@zhuhongweiyi 

I found my mistake when I generate lst file.
I used space to split item as https://github.com/fullfanta/CNN_based_Face_Alignment/blob/master/prepare_data/collect_augmented_images.py#L137-L139

But, in im2rec.py, they split item by '\t' as https://github.com/dmlc/mxnet/blob/master/tools/im2rec.py#L85

So, If you edit collect_augmented_images.py and regenerate lst file, you can use im2rec.py as 
`python im2rec.py --num-thread 32 --pack-label true training_data ./`

I'll check collect_augmented_images.py and commit it if it has no problem.

**Comment by zhuhongweiyi** [comment]
@fullfanta 
Thank you very much!
