### ISSUE TITLE
which network you refer to

### ISSUE THREAD

**Issue by zhuhongweiyi** [fullfanta/CNN_based_Face_Alignment#3]
Thank you for sharing the code!
Could you tell me which network you refer to?

**Comment by fullfanta** [comment]
@zhuhongweiyi 

I tested two networks : VGG and inception with BN.
In terms of inference time, VGG is better than inception-BN.
In terms of accuracy, inception-BN is better than VGG. But VGG also shows good performance.

In my opinion, VGG is good choice to start.
